<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Problem;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;

/**
 * ProblemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $metadata=null)
    {
        /** @var EntityManager $em */
        parent::__construct($em, $metadata==null?new Mapping\ClassMetadata(Problem::class):$metadata);
    }

    /**
     * @param Problem $problem
     * @return bool
     */
    public function takeProblem(Problem $problem){

        try {
            $this->_em->persist($problem);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Problem $problem
     * @return bool
     */
    public function changeProblem(Problem $problem){

        try {
            $this->_em->merge($problem);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Problem $problem
     * @return bool
     */
    public function removeProblem(Problem $problem){

        try {
            $this->_em->remove($problem);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }
}
